### ISSUE TITLE
有关 JWT 的 Stateless 改进

### ISSUE THREAD

**Issue by charlie0129** [e-dialect/hinghwa-dict-backend#116]
作为 JWT 应该是 Stateless 的，也就是说无论在哪台机器上，无论怎么重启，只要 secret 不变，那么认证结果就是相同的，i.e. 登录态不会变。（这是 JWT 的特性，也是在分布式环境中用 JWT 的必要性）

那么目前的实现（我大概看了下，可能我看的不对）将 JWT 的 token 存在内存中的 dictionary 中，判断过期就不是很合适，因为这样机器重启/换机器登录态就变了。

小建议：过期时间 `exp` 和签发时间 `iat` 是 JWT 的专有字段，所以签发时间和过期时间应当放在这两个字段里，存在 JWT 里面，认证时直接从 JWT 里面获取过期时间和当前时间对比，判读 Token 是否有效。（当然用户等级，例如管理员、普通用户等也是可以直接放在 JWT 里面的）

**Comment by FrogDar** [comment]
> JWT现已更新exp字段，超时时间为1小时

如果已经更新完的话，那就关闭这个议题？
