### ISSUE TITLE
创建 DTO模型 user_update

### ISSUE THREAD

**Issue by Norton-Lin** [e-dialect/hinghwa-dict-backend#138]
本issue设计创建DTO模型 user_update
该DTO模型涉及接口US0301

任务：
        1.创建DTO模型 user_update
        2. 重构相关接口并补充注释

**Comment by lin594** [comment]
DTO 模型 user_update 根本是一个伪命题，这是传入的参数，无需变成 DTO
如果你想重构 US0301 函数，那么可以继续保留这个 issue
如果你不想重构这个函数，那么可以直接关闭这个 issue
