### ISSUE TITLE
DTO 改造计划：`music_update`

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#140]
数据模型：`music_update`
涉及接口：`MC0103 更新音乐信息`

**Comment by lin594** [comment]
才发现和 #123 重复了

**Comment by lin594** [comment]
原来是 DTO 写错了……

**Comment by lll123github** [comment]
> 原来是 DTO 写错了……

哦哦我把apifox改一下

**Comment by lin594** [comment]
> > 原来是 DTO 写错了……
> 
> 哦哦我把apifox改一下

Apifox 一般来说不会去改他的呀？ 有一些整理只是小修小补、

**Comment by lll123github** [comment]
> > > 原来是 DTO 写错了……
> > 
> > 
> > 哦哦我把apifox改一下
> 
> Apifox 一般来说不会去改他的呀？ 有一些整理只是小修小补、

不是嗷，不改的话返回就是空来着（好像的确是空？）

**Comment by lll123github** [comment]
> > > 原来是 DTO 写错了……
> > 
> > 
> > 哦哦我把apifox改一下
> 
> Apifox 一般来说不会去改他的呀？ 有一些整理只是小修小补、

似乎我并不是那么了解）

**Comment by lin594** [comment]
如果说

> > > > 原来是 DTO 写错了……
> > > 
> > > 
> > > 哦哦我把apifox改一下
> > 
> > 
> > Apifox 一般来说不会去改他的呀？ 有一些整理只是小修小补、
> 
> 不是嗷，不改的话返回就是空来着（好像的确是空？）

如果原本是空就继续是空就好了
这个DTO是我弄错了qwq

**Comment by lll123github** [comment]
> 如果说
> 
> > > > > 原来是 DTO 写错了……
> > > > 
> > > > 
> > > > 哦哦我把apifox改一下
> > > 
> > > 
> > > Apifox 一般来说不会去改他的呀？ 有一些整理只是小修小补、
> > 
> > 
> > 不是嗷，不改的话返回就是空来着（好像的确是空？）
> 
> 如果原本是空就继续是空就好了 这个DTO是我弄错了qwq

我把它返回值恢复成空的了

**Comment by lll123github** [comment]
> 如果说
> 
> > > > > 原来是 DTO 写错了……
> > > > 
> > > > 
> > > > 哦哦我把apifox改一下
> > > 
> > > 
> > > Apifox 一般来说不会去改他的呀？ 有一些整理只是小修小补、
> > 
> > 
> > 不是嗷，不改的话返回就是空来着（好像的确是空？）
> 
> 如果原本是空就继续是空就好了 这个DTO是我弄错了qwq

应该TCP可以保障不会出错？

**Comment by lin594** [comment]
检查了一下 根本不需要弄 music_update 这个 DTO
