### ISSUE TITLE
鉴权 装饰器（decorator）写法

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#174]
现在的写法：
https://github.com/e-dialect/hinghwa-dict-backend/blob/cc94c657ca7c64e82d105ad6213619c6eb394935/hinghwa-dict-backend/utils/TokenCheking.py#L16-L57

然后在函数里面手动去调用这个来鉴权

但是实际上可以模仿 Spring 中的权限系统，通过添加注解的方式，@xxx权限，然后来做权限管理
[参考代码](https://github.com/frog-software/frogsoft-cms/blob/5959bdf5c3a9a2dc2c72ce2cf0f9548ecfa57f28/backend/src/main/java/com/frogsoft/frogsoftcms/controller/v1/api/UserController.java)
```java
@RolesAllowed( "a","b")
```

当然还要考虑到只支持某个用户自己的情况（还分两种，严格限制只能他本人，还是他本人or管理员）

需要先设计一套方案 然后再改写

**Comment by lin594** [comment]
我的评价是 不如 #257
