### ISSUE TITLE
之后增加功能：quiz模块，用户增加词条，新增管理员审核

### ISSUE THREAD

**Issue by lll123github** [e-dialect/hinghwa-dict-backend#179]
目前规划是只能管理员增加词条，之后可能可以实现用户增加词条，新增管理员审核模块

**Comment by lin594** [comment]
对于词条，现在不就是用户可以新增然后管理员审核吗？

**Comment by lll123github** [comment]
可能在此期间林志实现了

**Comment by lin594** [comment]
> 可能在此期间林志实现了

我和 dxw 在**五月份**就实现了这个功能，可参考 #77、#83  等 issue

**Comment by lll123github** [comment]
好的。这个issue是会议记录。可能记录有误

**Comment by lin594** [comment]
> 好的。这个issue是会议记录。可能记录有误

当时说的是 quiz 模块的这个功能，林志在 #185 完成了这个功能，但是当时还有瑕疵，剩下一些工作在 #189 
你可以去完成一下 #189

**Comment by lll123github** [comment]
好的，我在下班之后去看看
