### ISSUE TITLE
添加参数: AT0404接口需要添加用户名和用户头像参数

### ISSUE THREAD

**Issue by zzy2695s** [e-dialect/hinghwa-dict-backend#183]
AT0404接口需要添加两个参数
user.nickname    string
user.avatar          string(头像url地址)

![image](https://user-images.githubusercontent.com/106298834/195237077-0b10b9ac-7949-4e36-983c-406cbeec3cce.png)

**Comment by lin594** [comment]
@Norton-Lin 之前貌似说这个已经替换好了？

**Comment by Norton-Lin** [comment]
好了，还没pull,虽然就几行

**Comment by Norton-Lin** [comment]
现在就pull
