### ISSUE TITLE
后台管理 quiz 增加批量审核功能

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#189]
仿照文章审核界面添加审核按钮
![image](https://user-images.githubusercontent.com/20886330/200168535-47ba6db6-7e7f-425b-8339-938d27865152.png)

应该就在对应模块的admin.py里

**Comment by lin594** [comment]
而且审核似乎并没有真正起作用？

管理页面 是否审核 -》 是否通过审核
