### ISSUE TITLE
重构 US0301 并添加相关返回信息

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#198]
https://github.com/e-dialect/hinghwa-dict-backend/blob/f051becef717f6be1cddaffa320e2efc690090ed/hinghwa-dict-backend/user/views.py#L186-L336

**Comment by lin594** [comment]
可以先从重构user的其他部分开始，更简单一些

**Comment by lin594** [comment]
![image](https://user-images.githubusercontent.com/20886330/212687465-23698d08-2f27-45df-ae1d-208603d9cc81.png)

性能有点糟糕 得提升一下

**Comment by charlie0129** [comment]
这个界面大量的并发请求，会把后端直接干死，需要前端一起优化

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/55270174/212693406-594d175a-18cc-4971-bb7f-344f8220c32c.png">
