### ISSUE TITLE
邮箱验证码：在邮箱不存在的时候提供反馈

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#206]
用户以为他填的邮箱地址可以接收到邮件，但是实际上收不到，这个时候我们就要测试一下了

![Screenshot_2022-12-28-23-20-17-62_470b4cb16301e0ed7c107f89a0d69573](https://user-images.githubusercontent.com/20886330/209833809-f6cc0134-e2d1-4fb5-b23f-f9097ccfc375.jpg)

![Screenshot_2022-12-28-23-20-10-91_470b4cb16301e0ed7c107f89a0d69573](https://user-images.githubusercontent.com/20886330/209833824-13619b13-7cba-4a58-9064-6251abd9f6c3.jpg)

**Comment by Norton-Lin** [comment]
基于现行协议与技术，要验证一个邮箱是否存在必须向该邮箱发送邮件，随后通过发送与核对邮件信息 或检查退信来验证邮箱是否真实存在。
我们已经实现了通过向对方邮箱发送验证码，随后通过验证码来核对信息的服务
故无需进行进一步验证
