### ISSUE TITLE
用户语音上传榜单

### ISSUE THREAD

**Issue by lll123github** [e-dialect/hinghwa-dict-backend#208]

**Comment by lin594** [comment]
之前没有上传时间的，就统一设置为2023年1月1日0点0分吧 （默认值）

**Comment by lll123github** [comment]
> 之前没有上传时间的，就统一设置为2023年1月1日0点0分吧 （默认值）

我试一下为空行不行，担心之后如果要明着显示的话可能会带来不必要的麻烦

**Comment by lll123github** [comment]
> 之前没有上传时间的，就统一设置为2023年1月1日0点0分吧 （默认值）

但是这样的话就没办法本地测试了

**Comment by lin594** [comment]
> > 之前没有上传时间的，就统一设置为2023年1月1日0点0分吧 （默认值）
> 
> 我试一下为空行不行，担心之后如果要明着显示的话可能会带来不必要的麻烦

啥啥啥  为什么要设置为空行？

**Comment by lin594** [comment]
> > 之前没有上传时间的，就统一设置为2023年1月1日0点0分吧 （默认值）
> 
> 但是这样的话就没办法本地测试了

你就写上这一条就行了 没必要测试（你本地也测不出来）

**Comment by lll123github** [comment]
> > > 之前没有上传时间的，就统一设置为2023年1月1日0点0分吧 （默认值）
> > 
> > 
> > 我试一下为空行不行，担心之后如果要明着显示的话可能会带来不必要的麻烦
> 
> 啥啥啥 为什么要设置为空行？

30天的话可能会出问题

**Comment by lin594** [comment]
> > > > 之前没有上传时间的，就统一设置为2023年1月1日0点0分吧 （默认值）
> > > 
> > > 
> > > 我试一下为空行不行，担心之后如果要明着显示的话可能会带来不必要的麻烦
> > 
> > 
> > 啥啥啥 为什么要设置为空行？
> 
> 30天的话可能会出问题

其实我本来就想算他们的功绩的
那这样子 给他们算 2022年12月12日12:12的吧 这样肯定超过了一个月
