### ISSUE TITLE
录音审核筛选字段添加

### ISSUE THREAD

**Issue by 123daxian** [e-dialect/hinghwa-dict-backend#213]
录音审核要增加根据 是否审核 和 审核是否通过 两个条件来筛选语音的功能
希望给语音增加审核状态的字段（string类型）-已通过、不通过、未审核

ps：今天有根据现在有的granted和visibility来看看能否实现，但尝试了很久貌似不太行。。麻烦了

**Comment by lin594** [comment]
这个在前端利用服务封装自己插入吧
就不直接修改后端了（工期有限x）
