### ISSUE TITLE
QZ0203 测试题组卷

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#219]
为配合前端需要增加接口，具体见 Apifox 中的说明

![image](https://user-images.githubusercontent.com/20886330/211591420-90b99415-8460-4411-a60f-e7a8ef87aadb.png)

![image](https://user-images.githubusercontent.com/20886330/211591376-3daab687-4c31-4b08-a2cb-62ef3cf5e136.png)

**Comment by lin594** [comment]
@Norton-Lin @lll123github 你们俩谁负责一下

**Comment by Norton-Lin** [comment]
我来吧
