### ISSUE TITLE
每日一词到期了没有更新

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#223]

**Comment by lin594** [comment]
正式服务器里停止在了1月7日
![image](https://user-images.githubusercontent.com/20886330/211986290-2686486c-b27d-417a-a240-1acd489c2d0d.png)

**Comment by lin594** [comment]
测试服务器停止在1月13日
![image](https://user-images.githubusercontent.com/20886330/211986393-8b2e3dfc-9948-41d2-844b-bfff05ec1f96.png)

**Comment by Norton-Lin** [comment]
疑似由对应定时任务执行函数register_event被弃用导致
正在寻找修复方法

**Comment by Norton-Lin** [comment]
后台管理中经手动运行后，正式服务器已可以执行定时任务
![QQ截图20230115001011](https://user-images.githubusercontent.com/75243447/212482264-a801c67d-1787-427a-80a6-93db4891aa32.png)
