### ISSUE TITLE
字典查询

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#231]
![image](https://user-images.githubusercontent.com/20886330/212084023-e22fc1d4-c2a2-49d1-8802-b0ae40f605ec.png)

![image](https://user-images.githubusercontent.com/20886330/212084067-52d29fb1-14e8-4226-9565-81e3c324bd5e.png)

两个接口里总有一个有问题吧）

话说建立 trie 树的时候有考虑 visibility 吗？我感觉可能没有？

**Comment by Norton-Lin** [comment]
该问题由三条特殊数据造成
形如：
[](![%6`IAYOHCVC7P)T0J$}HW B](https://user-images.githubusercontent.com/75243447/212098742-917756a2-3900-44f2-8c14-0f56bc653017.png))

standard_pinyin字段内数据格式不规范，将在数据库内进行修改
