### ISSUE TITLE
语音审核模块可能有问题

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#237]
每次重新启动之后原本的审核记录都会消失？
是不是审核人这个字段没有保存好？
需要重新审查这部分的代码，要不然又要重新审核一次又一次的、

**Comment by Norton-Lin** [comment]
你是说，重启之后，已审核过的结果都会消失么？恢复到审核前的状态

**Comment by lin594** [comment]
数据库莫名出问题，通过修改数据库解决该问题
