### ISSUE TITLE
上传文件格式

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#244]
https://github.com/e-dialect/hinghwa-dict-backend/blob/f0f1f097f08f86c33be82c61c6c6f28af8d57a82/hinghwa-dict-backend/website/views.py#L405-L413

使用 `uni-app` 的接口上传图片的时候会得到后缀名 mp3

**Comment by Norton-Lin** [comment]
uni-app接口上传图片时，能否查看一下所上传文件对应的content-type
![image](https://user-images.githubusercontent.com/75243447/212462713-5e0b1681-b22b-4989-979b-4646c2f07c9c.png)
content_type类似上图，截取于apifox内的实际请求
http请求内会显示该字段

**Comment by lin594** [comment]
是前端的代码写错了）） 呜呜
