### ISSUE TITLE
quiz 默认语音

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#248]
![image](https://user-images.githubusercontent.com/20886330/212472366-5cf65f81-4563-4a02-80af-becc73cd5448.png)

quiz 怎么默认返回的是 这个东西

**Comment by lin594** [comment]
不是说应该返回 `null` 或者 `""` 的吗？

**Comment by lll123github** [comment]
说是哪个接口呢

**Comment by lin594** [comment]
之前旧数据库在迁移的时候  这个默认值出现问题  应该是默认填充 null 或者 ‘’ 的，但是现在默认填充了 `voice_source`

**Comment by lin594** [comment]
应当是迁移文件出了问题，代码本身没有问题

**Comment by lll123github** [comment]
在查看迁移文件和代码之后，和大青蛙没有找到代码中的问题，在本地迁移并未复现测试服务器中的情形
