### ISSUE TITLE
语音排行榜接口

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#249]
- [x] 不需要权限 #250
- [x] 仅查询已经通过审核的语音 #252
- [ ] 将缓存 JSON 改为 缓存 结果数组（根据下一条，缓存的逻辑需要稍微改改、）
- [ ] 添加查询自己排名位次的字段（比如加一个 me: xxx ） 代表自己是多少名  （没登录的返回0）

**Comment by lll123github** [comment]
有一个问题，就是如果遇到排名并列的话应该怎么办呢

**Comment by lin594** [comment]
这是一个好问题
我的建议是按照最后一条语音的贡献时间，早的排名靠前
不过这样的话，缓存的数组就得再加一个字段（感觉问题不大）
