### ISSUE TITLE
迁移文件整理

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#251]
应当是迁移文件出了问题，代码本身没有问题

_Originally posted by @FrogDar in https://github.com/e-dialect/hinghwa-dict-backend/issues/248#issuecomment-1382870856_
            

迁移文件的长时间不更新导致迁移屡屡受挫
需要部分更新仓库中的迁移文件

**Comment by lin594** [comment]
![image](https://user-images.githubusercontent.com/20886330/212488194-e659203b-e226-4211-ac9a-436102fd6141.png)

造成语音审核情况丢失
造成 quiz 的 author 模块无法添加
