### ISSUE TITLE
认证模块中间层

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#257]
https://docs.djangoproject.com/en/3.1/ref/middleware/#module-django.contrib.auth.middleware
https://docs.djangoproject.com/en/3.1/topics/auth/default/#auth-web-requests

利用认证模块中间层或许是比现有的手写 token 认证更好的方法）

**Comment by lin594** [comment]
便利的中间件方案用的是 session
JWT 的话已经学习到一个新的写法或许更好一些
