### ISSUE TITLE
前端联调错误

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#281]
https://github.com/e-dialect/hinghwa-dict-web/issues/103
创建词条在前端进行修改之后，实际写入的数据不正确，暂时未知是前端还是后端的错误

**Comment by lin594** [comment]
![image](https://user-images.githubusercontent.com/20886330/217746230-6db97700-04b7-4d0b-94cc-1f28fb1f5e3f.png)

创建词语后出现两次词语

**Comment by lin594** [comment]
@Norton-Lin 你要是有空的话 可以先排查一下 这个是前端的问题还是后端的问题
