### ISSUE TITLE
实现两个文章评论接口

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#283]
![image](https://user-images.githubusercontent.com/20886330/215316112-52797a3c-70a7-40fc-a707-2da907e91671.png)

- [ ] #289 
- [x] #290

**Comment by Norton-Lin** [comment]
简单来说就是，首先查看一下你们的APIFOX，找到AT0405、AT0406两个接口的定义，定义中给出了参数和返回值类型，请根据这两个接口的定义，完成接口功能的编写（利用参数，实现逻辑，返回数据）
