### ISSUE TITLE
CH0301 文件批量添加

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#284]
CH0301 文件批量添加
POST /characters/add
接口ID：5507301
接口地址：https://www.apifox.cn/web/project/404238/apis/api-5507301

路径估计有问题

**Comment by lin594** [comment]
这个其实我本地都简单的修到能用了）
但是你可以稍微重构一下下x
大概应该是路径不太对的原因2333

**Comment by Norton-Lin** [comment]
答辩完我看看

**Comment by Norton-Lin** [comment]
问题源自xlrd2.0.1版本不再支持xlsx文件，可以采用xls文件进行上传
