### ISSUE TITLE
quiz 语音上传工具

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#287]
> 在根目录下增加 `tools` 文件夹用来存放各类小工具（记得脱敏，不要携带任何 `token` 之类的信息） -》 这点稍微完善一下帮忙搞成 README

quiz 语音上传工具的预期使用方法：
读取一个文件夹内所有的语音（名字可能叫做 `xxx.m4a` 或者 `xxx.mp3`），那么就对 xxx 编号的 quiz 增加语音来源`https://cos.edialect.top/quizzes/xxx.m4a` 或 `https://cos.edialect.top/quizzes/xxx.mp3`

单独给这个工具在 tools 里创建一个子文件夹并附上 README

同时，在 `tools` 文件夹里创建一个表格，快速索引这个工具（文件夹是xxx，功能大概是xxxx）

**Comment by lin594** [comment]
脱敏的方式：
- 最粗暴的方法：执行的时候字符串有值，不执行的时候为空
- 优雅一点的方法：环境变量
