### ISSUE TITLE
似乎修改密码还是有问题

### ISSUE THREAD

**Issue by lll123github** [e-dialect/hinghwa-dict-backend#288]
报错500

**Comment by lin594** [comment]
尽快修复  或者不能修复的话 把更具体的一些报错内容说明一下

**Comment by Norton-Lin** [comment]
说明一下具体问题谢谢

**Comment by lin594** [comment]
> 说明一下具体问题谢谢

大概来说 就是他自己尝试使用“忘记密码”功能的时候 发现流程走不完23333

**Comment by lll123github** [comment]
目前只是在操作过程中网页进行如下的报错：
![image](https://user-images.githubusercontent.com/97929788/225655777-ffcc43dc-8185-42d3-847d-8051ab807ef6.png)
还并没有思考如何获取到更详细的报错情况

**Comment by lin594** [comment]
> 目前只是在操作过程中网页进行如下的报错： ![image](https://user-images.githubusercontent.com/97929788/225655777-ffcc43dc-8185-42d3-847d-8051ab807ef6.png) 还并没有思考如何获取到更详细的报错情况

那当然是你自己在本地开发模式里 通过各种方式（包括但不限于直接返回、输出日志） 来显示一些小内容

**Comment by lin594** [comment]
明确为 #307
