### ISSUE TITLE
AT0405 获取评论详情

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#289]
AT0405 获取评论详情
GET /articles/comments/{id}
接口ID：59289042
接口地址：https://www.apifox.cn/web/project/404238/apis/api-59289042

![image](https://user-images.githubusercontent.com/20886330/225212947-795a7705-9ee7-4116-b599-467b2ae5911d.png)

**Comment by Norton-Lin** [comment]
这个有没有人要啊，没人要我领了啊

**Comment by lin594** [comment]
> 这个有没有人要啊，没人要我领了啊

简简单单的东西留给他们去做吧）
