### ISSUE TITLE
AT0406 删除评论（和子孙评论）

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#290]
AT0406 删除评论（和子孙评论）
DELETE /articles/comments/{id}
接口ID：59289286
接口地址：https://www.apifox.cn/web/project/404238/apis/api-59289286

管理员或本人才能删除！
返回的格式可以略微调整，按照需要进行

**Comment by Norton-Lin** [comment]
诶，这接口AT0402不是有了么

**Comment by lin594** [comment]
哦 确实  只是那个设计太不 RESTful 了
算了 那就不要这个了
