### ISSUE TITLE
微信小程序注册bug

### ISSUE THREAD

**Issue by CapooL** [e-dialect/hinghwa-dict-backend#317]
当用户在微信注册界面就更换头像时，第一次注册会显示“资源不存在”
![_2b1abd907dd3cd78469e5419435ea63d_-430462063_qq_pic_merged_1691248387399](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/de0f9462-fad3-4715-9af5-7a7a7ec3564b)
再次尝试会显示“用户名重复”
![_be330e19505ec631c4f97037330224ac_1376068879_qq_pic_merged_1691248377398](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/1429f87e-340a-4184-9eca-a3b260b080fc)

**Comment by lin594** [comment]
这个主要也是前端跟着修复 https://github.com/e-dialect/hinghwa-dict-uni-app/pull/184 来修复的
