### ISSUE TITLE
统一审核邮件格式

### ISSUE THREAD

**Issue by Shxuuer** [e-dialect/hinghwa-dict-backend#321]
为了方便前端正则匹配审核邮件，实现跳转功能，希望能够在审核邮件中统一一下id显示格式
![图片](https://github.com/e-dialect/hinghwa-dict-backend/assets/72177904/9bc4f9a1-e05a-4709-9cab-29e09fcb8f87)

针对于此类邮件，将id显示格式统一为以下格式
```
语音(id=123)
```
其中，语音与括号之间、等号周围没有空格，括号为英文半角括号。
类似的，对于词条审核、语音审核、修改审核都应应用此类格式

**Comment by lin594** [comment]
新增加的已经可以了，存量的还未替换
