### ISSUE TITLE
通知中真正关联相应的操作

### ISSUE THREAD

**Issue by FrogDar** [e-dialect/hinghwa-dict-backend#329]
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/a3ef6fe3-ded0-45b1-8022-3cbcdc707aa4)

现在的封装似乎并不是一个好做法，没有把真正的业务对象捆绑到通知里

**Comment by lin594** [comment]
@CapooL 你把你的解释丢在这个地方）

**Comment by CapooL** [comment]
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/39c1699c-539e-4dc6-a570-630a5b57efa1)
原来的可能也没错）应该是我之前的理解出问题了
