### ISSUE TITLE
词语-标签字段

### ISSUE THREAD

**Issue by lin594** [e-dialect/hinghwa-dict-backend#348]
那个tag就是每个词条都有的属性，一个词条可以有多个tag，允许手动添加编辑删除。然后可以通过tag作为条件去筛选词
![8082598f93d470f70ea07a2bd72b1f60](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/63d00b0a-3a6d-449c-85cb-0c16f10b47fe)

点进天文tag，就转入那个search页面，只不过是 tag=天文
![f82ba1600d73678e20a2050b4912203a](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/b7bb91cf-5ba7-4f30-9825-edd04a4bd839)
如果可以的话，高级搜索，支持 ?tag=天文&key=太阳

**Comment by Norton-Lin** [comment]
#   word模块 增加tag字段以及相关功能
##  字段本身
-   word 添加tag字段 
    -   此处修改dto、models
    -   若需要对tag进行单独处理，则修改word模块对应接口
##  字段属性
-   初步筛选
    -   通过tag字段进行筛选
        -   增加接口WD0203 根据tag进行筛选  url: /words/search?tag=xxx(推荐)
        -   或者修改接口WD0201，增加tag字段 (不推荐)
-   高级筛选
    -   在tag过滤后的基础上进一步过滤
        -   url: /words/search?tag=xxx&key=xxx

##  补充
-   考虑到多级tag的情况，tag字段应该是一个数组或字典
    -   一级tag: 大类型 二级tag: 小类型
    -   eg: tag: [生物, 动物, 猫科, 家猫~]
-   tag字段的增加，需要考虑到tag的维护
    -   故需要考虑WD0102、WD0103接口逻辑的增加

**Comment by lin594** [comment]
tag字段直接选用数组吧，然后在 WD0201 上添加一个 filter 用来过滤（词语的标签列表里包含这个tag）

**Comment by CapooL** [comment]
现在后端用的数据库是sqlite,django的ArrayField限定后端数据库为pgsql，现在解决方案为tag字段用TextField进行数据存储，在dto里使用json.loads()将字符串转为list格式，效果如下：
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/76fe1818-07bb-4027-b9ad-bdec5f40025d)
查询tags时，使用filter中的__icontains进行查询：
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/b30c0c3a-acec-4400-855d-777d442758c6)

**Comment by lin594** [comment]
> tag字段用TextField进行数据存储，在dto里使用json.loads()将字符串转为list格式

这个不是第一次在本仓库出现了，很正常hh，就这么干

> 查询tags时，使用filter中的__icontains进行查询

没有理解是怎么查询的？不过我觉得比如查询接口里有某个东西就应该返回包括这个tag的词语，如果一次填了两个词语呢，出现一个就返回？

**Comment by CapooL** [comment]
>没有理解是怎么查询的？不过我觉得比如查询接口里有某个东西就应该返回包括这个tag的词语，如果一次填了两个词语呢，出现一个就返回？

icontains是过滤出包含query子串的字段模型
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/1af95570-90ad-4cfb-8ef5-c1816f542ed4)
一次填两个词语(是不是应该是tag?)，我是把tag都提取出来，然后一个一个去过滤匹配，不过最后结果是混杂在一起的，要是每个tag查询的内容分开的话，代码得稍微变一下
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/12d52824-41e8-48a1-b077-cafc56491cf8)
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/f97ec51a-3244-429e-aef1-a7ef569b47f1)

**Comment by CapooL** [comment]
> 一次填两个词语(是不是应该是tag?)，我是把tag都提取出来，然后一个一个去过滤匹配，不过最后结果是混杂在一起的，要是每个tag查询的内容分开的话，代码得稍微变一下 

查询结果分开大致效果图(省略了点信息)：
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/111524029/0381a100-9ec3-4569-80b1-d190c96a96a7)

**Comment by lin594** [comment]
> 一次填两个词语(是不是应该是tag?)，我是把tag都提取出来，然后一个一个去过滤匹配，不过最后结果是混杂在一起的，要是每个tag查询的内容分开的话，代码得稍微变一下

其实我觉得混在一起就行吧23333
分开感觉意思上怪怪的，不如直接查询两次

**Comment by CapooL** [comment]
> 其实我觉得混在一起就行吧23333 分开感觉意思上怪怪的，不如直接查询两次

行
