### ISSUE TITLE
单字优化

### ISSUE THREAD

**Issue by lin594** [e-dialect/hinghwa-dict-backend#349]
、是单字的每一个读音，能否加一个属性，展示这个读音的type。比如：文读、白读、训读、俗读、新读  等类型，null的时候就不显示咯

![5f3a1c0f7ee7e423375e989c02da303f](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/913b21ab-2145-4f59-be97-0352682a66c0)

此外，如果有什么用到这个音的词，你点他一下，进入到那个搜索列表，这个列表显示的都是 这个字读这个音的

**Comment by Norton-Lin** [comment]
#   character模块 及相关功能
##  增加type字段
-   修改character模块的models和dto
##  增加根据读音搜索对应词语
-   过滤出所有该字发这个读音的词/字
-   建议word模块增加一个接口WD0204...
-   核心问题是如何传递这个发音，并在word中检索该字是否为该发音
