### ISSUE TITLE
拼音快速搜索

### ISSUE THREAD

**Issue by lin594** [e-dialect/hinghwa-dict-backend#353]
新增加一个接口，能够自动拆分搜索串里的合法拼音并把他进行搜索

如果是 yng 就搜索 所有声调
如果是 yng3 就搜索 对应的那个声调
尽量支持模糊音、

![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/8c28a742-9b11-4bf6-98c4-4104642d3e39)

**Comment by Norton-Lin** [comment]
在支持模糊搜索的情况下，识别用户输入的合法拼音，并进行搜索
没有声调的情况下，查询所有声调。
有声调的情况下，只查询该声调。
并对搜索结果进行排序。

**Comment by lin594** [comment]
对后端的需求来说 更像是 输入为字符串，输出为

![44e8388f811701ae55bccc7b7aad03a8](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/5f945c56-3d3d-4b7c-b1c2-deaba14024ea)

如果能兼顾入声声调就更好了
比如 gi1 gi2 gi3 gi4 gi5 gih6 gih7 入声的写法上有一点点区别

**Comment by lin594** [comment]
对前端的需求就是多一个用拼音查汉字的模块（有线现有组件）

![6953302cbc8d4c9e5673bad3eb9b3286](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/f03fed2d-5cd3-41a2-aa64-e225dd8a47f2)

![44e8388f811701ae55bccc7b7aad03a8](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/eeab1a6d-139a-46a3-b3c5-13a72514cb8d)

**Comment by Topology2333** [comment]
> 这个拼音查汉字，是相当于拼音输入法吗？
> 有什么必要吗（

不是啊，这就是查询的结果，你可以理解为单纯就是为了提升用户体验，让他们不需要一个一个点出来查找
