### ISSUE TITLE
建议readme补充上对应python版本环境

### ISSUE THREAD

**Issue by zxj5470** [e-dialect/hinghwa-dict-backend#360]
对于 setuptools 和 pip 版本可能有要求。

Python安装demjson模块报错：error in demjson setup command: use_2to3 is invalid

https://blog.csdn.net/qq_42971035/article/details/129655525

```
python -m pip install --upgrade pip
pip install --upgrade setuptools==57.5.0
```

目前个人测试正常版本 
```
python 3.8
pip==24.0.0
setuptools==57.5.0
```

**Comment by lin594** [comment]
因为以前这个仓库主要对内使用，所以用口口相传的方式把版本写在[这里](https://github.com/e-dialect/hinghwa-dict-backend/blob/develop/hinghwa-dict-backend/requirements.txt)
这个问题也关注到了，因为之前使用了很老版本的 `demjson` 导致了一系列问题
在 https://github.com/e-dialect/hinghwa-dict-backend/pull/359 中将更换为 `demjson3` 来解决这个问题
